include:
  # QWERTY BT
  - board: nice_nano_v2
    shield: charybdis_left
    keymap: qwerty
    format: bt
    
  - board: nice_nano_v2
    shield: charybdis_right
    keymap: qwerty
    format: bt
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y  

  # QWERTY Dongle
#  - board: nice_nano_v2
#    shield: charybdis_left
#    keymap: qwerty
#    format: dongle

#  - board: nice_nano_v2
#    shield: charybdis_right
#    keymap: qwerty
#    format: dongle

#  - board: seeeduino_xiao_ble
#    shield: charybdis_dongle
#    keymap: qwerty
#    format: dongle

  # Firmware Reset
  - board: nice_nano_v2
    shield: settings_reset
    format: reset